shobhi1310/backend-team

.gitignore, models/Event.js, routes/users.js, server.js
GridFS routes added
Image Handling
Fixed merge issues
=> Image workflow

models/Event.js, routes/events.js, server.js
=> EventSummary

routes/users.js, server.js
commeted wherever necessary and minor changes
=> commented 

routes/admin.js, server.js, views/adminControls.ejs, views/adminLogin.ejs
Added **routes**.
Also added paths and **ejs** for success failure and **auth level**.
=> Added adminLogin

.vscode/settings.json, server.js, views/profile.ejs
=> redesigned profile.ejs

models/SuperAdmin.model.js, routes/admin.js, server.js, views/adminLogin.ejs, views/index.ejs
Fixed Login logic.
Added fall through and implementing ejs.
Fixed a few errors.
=> Login Updation

routes/users.js, server.js
Image upload and profile update route repaired.
Fixed Obsoluete routes and conflicts.
=> Profile Image Route

routes/admin.js, views/view_club_heads.ejs
Added a route via club model.
Added an ejs to display it dynamically.
=> Viewing Club Head

routes/users.js, server.js, views/add_event.ejs, views/event_view.ejs, views/public_landing.ejs
Event routes updated.
Tested with actual poster (might need to contol the flexibity in that)
=> Fixed event adding/view routes

routes/admin.js, server.js, views/admin_landing.ejs, views/admin_updateprof.ejs, views/create_achievement.ejs, views/create_club.ejs
created some views and routes in admin.js .  Few changes yet to be done
=> created routes for buttons in admin_landing

routes/users.js, views/event_details.ejs, views/event_view.ejs
Added view
Added and fixed required Routes
Included new commits.
=>  Event Details

routes/events.js, views/update_event.ejs
Update Event fields completed.
Modified the poster option.
=> Prefilling entries

routes/admin.js, routes/users.js, server.js, views/add_event.ejs, views/adminLogin.ejs, views/admin_landing.ejs, views/admin_updateprof.ejs, views/create_achievement.ejs, views/create_club.ejs, views/event_view.ejs, views/public_landing.ejs, views/updateprof.ejs, views/view_club_heads.ejs
I tried to fix the conflicts as much as i can have a look to it once though.
=> added the session in admin and users

routes/users.js, server.js, views/add_event.ejs, views/update_event.ejs, views/updateprof.ejs
Unified updation route.
Added preview to updated image without  need to reload.
Fixed Add event
Checked and fixed 2 situations that would cause app to crash.
=> Image Routes & Fixes

routes/admin.js, server.js, views/admin_landing.ejs, views/project_details.ejs, views/view_achievement.ejs
View Created
Routes Mapped
Fixed encountered bugs
=> Project Details

routes/admin.js, server.js, views/create_project.ejs, views/project_details.ejs
Changed project route based on new logic.
Added multiple image uploads.
Slight Fixes
=> Updated Projects

server.js, views/add_event.ejs, views/create_project.ejs, views/update_event.ejs
Added dropdowns
Added prefill for updation in select
Redirection updated
Disabled default added to selection
=> Updates to input system

server.js, views/create_achievement.ejs, views/create_project.ejs
Achievement & Project updated
Image checker now removes from buffer.
Added mechanic which can add multi queries as well.
=> Image Routes update

routes/admin.js, server.js, views/create_club.ejs
Added logo uploading
Fixed route
=> FIx Club route

routes/admin.js, server.js, views/update_achievement.ejs
i've  removed a route in admin.js '/admin/achievement/update/:id' and created a route in server.js to update achievement
=> created routes to update achievement

routes/admin.js, server.js
(placed it server for uploads)
=> fixed the project/update route

server.js, views/update_club.ejs
Route added.
Linked routes.
Fixed view and params.
=> Added Club update

server.js, views/project_details.ejs, views/project_update.ejs
Route fixed
Removed a few errors
Redirect updated
=> Fix Project

routes/admin.js, routes/events.js, routes/images.js, routes/users.js, server.js, views/adminLogin.ejs, views/admin_updateprof.ejs, views/password.ejs
->Images:
Exported module
Shifted to corresponding routes
->Admin prof : fixed errors
->Added confirm password
->Added update route
Linked view
Fixed redirects
-> Invalid Login Alerts added
=> 4 Issues addressed + fixes & routes

routes/images.js, views/add_event.ejs, views/add_summary.ejs, views/create_achievement.ejs, views/create_club.ejs, views/create_project.ejs, views/project_update.ejs, views/update_achievement.ejs, views/update_club.ejs, views/update_event.ejs, views/updateprof.ejs
Limit image uploads at client as well as server restriction.
Server now allows only jpeg, jpg, png and gif
Also added a file size limit.
=> Image Limit

routes/events.js, views/add_summary.ejs, views/event_details.ejs
Fixed Route
Updation with multi image
Added display in view
=> Event Summary Fix

models/ClubHead.model.js, routes/achievements.js, routes/admin.js, routes/club.js, routes/club_head.js, routes/event_summary.js, routes/events.js, routes/images.js, routes/notify.js, routes/projects.js, routes/register.js, server.js, storage.js, views/contact.ejs, views/create_event.ejs, views/create_summary.ejs, views/details_event.ejs, views/index.ejs, views/landing_clubHead.ejs, views/update_event.ejs, views/update_profile_clubHead.ejs, views/update_summary.ejs, views/view_events.ejs
Linked new routes
Updated routes to new format
Fixed few issues
Added routes for summary creation
Prefilled most updation
Changed to CamelCase and made uniform
=> New Routes and fixes

routes/admin.js, routes/club.js, routes/events.js, routes/projects.js, server.js, views/contact.ejs, views/create_club.ejs, views/create_event.ejs, views/details_club.ejs, views/details_event.ejs, views/details_project.ejs, views/index.ejs, views/landing_admin.ejs, views/landing_clubHead.ejs, views/update_achievement.ejs, views/update_club.ejs, views/update_event.ejs, views/update_password_clubHead.ejs, views/update_profile_clubHead.ejs, views/update_project.ejs, views/view_achievements.ejs, views/view_clubs.ejs, views/view_events.ejs
Fixed :
Broken Routes
Missed out changes
Naming changes
=> Minor FIxes

routes/blog.js, views/create_blog.ejs, views/update_blog.ejs, views/view_blog.ejs
Updated video links to array
Prevented Null updates due to tables.
File name updated : consistency
=> Blog Update

routes/achievements.js, routes/admin.js, routes/club.js, routes/club_head.js, routes/projects.js, views/create_achievement.ejs, views/create_club.ejs, views/create_club_head.ejs, views/create_project.ejs, views/details_club.ejs, views/details_project.ejs, views/landing_admin.ejs, views/partials/navbar_admin.ejs, views/reset_club.ejs, views/update_achievement.ejs, views/update_password_admin.ejs, views/update_profile_admin.ejs, views/update_project.ejs, views/view_achievements.ejs, views/view_club_heads.ejs, views/view_clubs.ejs, views/view_projects.ejs
Added admin navbar partial
Linked all required pages
Added highlight to active tab
Fixed few issues
=> Admin Navbar

db/upload.js, routes/admin.js, routes/club_head.js, views/adminLogin.ejs, views/index.ejs
File limit updated
Club Head partial component fix
Club Head Image route error corrected
Reject white space in login form
Made the fields required inputs.
Separated login errors to existing handler.
=> Addressing Issues

models/Event.model.js, routes/events.js, routes/notify.js, views/details_event.ejs, views/view_events.ejs
Checking date of event maturity before any edits.
Implemented client view checks
Added server side denials for illegal requests
Removed unused field
Image dragging block for events
=> Date Validation

models/Event.model.js, routes/events.js, views/view_events.ejs
=> Filtered Front-End

views/create_club.ejs, views/create_event.ejs, views/create_project.ejs, views/details_club.ejs, views/details_event.ejs, views/details_project.ejs, views/update_club.ejs, views/update_event.ejs, views/update_project.ejs, views/view_clubs.ejs
Updated all places with a description input
=> Editor box

routes/blog.js, views/create_blog.ejs, views/update_blog.ejs, views/update_event.ejs, views/view_blog.ejs
Dropdown in Blogs
Selective visibility
Create/Update routes updated
=> Category based

routes/club.js, routes/events.js, views/create_club.ejs
=> Club Admin

routes/blog.js, views/create_achievement.ejs, views/create_blog.ejs, views/create_project.ejs, views/update_project.ejs
File selection onload updated
Earlier system i made had lot of issues
New system rectifies the wrong deletions
Added system to blog create
=> New Gallery Script

models/ClubMember.model.js, routes/club_members.js, server.js, views/create_club_member.ejs, views/partials/navbar_clubhead.ejs, views/update_club_member.ejs, views/view_club_members.ejs
Views linked
New routes added for club member
Issues fixed
=> Member Routes

routes/supporting/contestFetcher.js, server.js, views/view_contests.ejs
Added a view to view open contests.
Alternative js with routes added.
Utilizes 3 sources so should be okay for our needs.
=> Contests Workaround

routes/blog.js, routes/front.js, views/create_blog.ejs, views/update_blog.ejs, views/view_blogs.ejs
Updation and creation of published param.
Logical update for featured.
Filter for frontend.
Fixes to errors encountered.
=> Published param

routes/club_head.js
Issue fixed
Method used not as per model design.
Now passwords are encrypted on update.
=> Fix clubhead updates

routes/club_head.js
Reverts shobhi1310/backend-team#121
=> Revert "Fix clubhead updates"

routes/tech_teams.js, views/create_tech_team.ejs, views/partials/navbar_admin.ejs, views/update_tech_team.ejs
=> created views for tech_team

middleware/adminAuth.js, middleware/clubAuth.js, models/Event.model.js, routes/blog.js, routes/club.js, routes/club_head.js, routes/club_members.js, routes/events.js, routes/supporting/images.js, views/update_blog.ejs, views/update_event.ejs
Prefill format err
Missed out error points
File deletion to events route.
Image 404 bypass
Required field unmarked (need another client method)
=> Event Update

routes/club.js, routes/front.js, views/update_club.ejs
New params added
Routes and view updated accordingly
=> Club update

routes/committee.js, views/partials/navbar_admin.ejs
=> Navbar update

.gitignore, routes/achievements.js, views/create_achievement.ejs, views/create_blog.ejs, views/create_club_member.ejs, views/create_committee_member.ejs, views/create_event.ejs, views/create_project.ejs, views/create_tech_team.ejs, views/partials/dependencies.ejs, views/partials/image_compressor.ejs, views/partials/multi_image_handler.ejs, views/pub_create_blog.ejs, views/pub_create_project.ejs, views/update_achievement.ejs, views/update_blog.ejs, views/update_club.ejs, views/update_club_member.ejs, views/update_committee_member.ejs, views/update_event.ejs, views/update_profile_clubHead.ejs, views/update_project.ejs, views/update_tech_team.ejs, views/view_achievements.ejs
Compression added for all image upload routes.
Logical changes as necessary for the 3 types of img uploads.
Views and routes updated.
Partials created for ease of maintenance
Minor Error Fixes
Only bypass for compression is as a file attachment (intended backdoor)
=> Image compression all

routes/front.js
=> Chainable Queries

routes/front.js
Added filter for frontend ease
=> Achievements Update

routes/blog.js, routes/editor.js, views/adminLogin.ejs, views/blog_editor.ejs, views/details_blog_editor.ejs, views/index.ejs, views/partials/navbar_editor_blog.ejs, views/update_blog.ejs, views/update_blog_editor.ejs, views/view_blogs_editor.ejs
All routes and views of editor updated
Routes linked and deletion integrated into update and dedicated
Error Fixes
=> Blog Editor : Full update

routes/editor.js, views/update_blog_editor.ejs
Route update to incorporate changes.
Fixes
=> Editor Updates

package.json, routes/achievements.js, routes/blog.js, routes/events.js, routes/projects.js
Changes made to query sent to monkey learn as suggested.
Updated in all places monkey learn was in use
P.s. New dependency added for dom methods.
=> Monkeylearn Update

routes/challenges.js, routes/front.js, views/create_challenge.ejs, views/update_challenge.ejs
Options queried and added to challenges create and update views
Added front end route for query :
- Usage without secondary param 
/front/challenges/:category (has support for "all" as well)
- Usage with secondary param (optional)
/front/challenges/all?exp=only (returns only expired challenges / registration closed)
/front/challenges/all?exp="any other value" returns all open challenges
=> Challenges : Options

routes/front.js, views/create_blog.ejs
front/categories/:target
target can currently be challenge branch or blog.
optional param all can be passed as long as it is defined (?all=true) it will return a static reponse containing all the defined components
Contributions frontend updates included.
=> Categories : Front end

routes/front.js
Added required route to return array of blog ids.
=> Tags Filter

routes/blog.js, routes/projects.js, views/adminLogin.ejs, views/blog_editor.ejs, views/create_achievement.ejs, views/create_blog.ejs, views/create_challenge.ejs, views/create_event.ejs, views/create_news.ejs, views/create_project.ejs, views/create_tech_team.ejs, views/index.ejs, views/pub_create_blog.ejs, views/pub_create_project.ejs, views/update_achievement.ejs, views/update_blog.ejs, views/update_blog_editor.ejs, views/update_challenge.ejs, views/update_club.ejs, views/update_event.ejs, views/update_news.ejs, views/update_project.ejs, views/update_tech_team.ejs
Ckeditor centered errors fixed.
Blog incorrect tagging fixed.
Login pages redesigned.
=> Issue Fixes & login page
